server:
  port: 4000
spring:
  application:
    name: leeyen-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  freemarker:
    cache: false
  redis:
    host: 127.0.0.1
  session:
    store-type: redis

short:
  message:
    host: https://dfsns.market.alicloudapi.com
    path: /data/send_sms
    method: POST
    appcode: f7ce7b518cb3486a841bf5b57b21d221
    template-id: TPL_0000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

